name: .NET Build (VB)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x' # Change if your project uses a different version

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    # Optional: Add test step if you have tests
    # - name: Test
    #   run: dotnet test --no-build --verbosity normal

    - name: Build succeeded!
      if: success()
      run: echo "Build finished successfully!"
